routes/admin.php
<?php

Route::get('/', 'HomeController@index')->name('dashboard');

Route::get('/department/data', 'DataController@departments')->name('department.data');
Route::resource('/department', 'DepartmentController');

Route::get('/position/data', 'DataController@positions')->name('position.data');
Route::resource('position', 'PositionController');

Route::get('/category/data', 'DataController@categories')->name('category.data');
Route::resource('category', 'CategoryController');

Route::get('/employee/data', 'DataController@employees')->name('employee.data');
Route::resource('employee', 'EmployeeController');
Route::get('/employe/data/first','DataController@employeesFirst')->name('employee.data.first');
Route::get('/employe/data/first/view','EmployeeController@employeesFirstView')->name('employee.data.first.view');

Route::get('/absent/data', 'DataController@absents')->name('absent.data');
Route::resource('absent', 'AbsentController');

Route::get('/benefit/data', 'DataController@benefits')->name('benefit.data');
Route::resource('benefit', 'BenefitController');

Route::resource('laporan', 'LaporanController');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

app/Employees.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employees extends Model
{
    protected $guarded = [];

    public $timestamps = false;

    public function department()
    {
        return $this->belongsTo(Departments::class);
    }

    public function position()
    {
        return $this->belongsTo(Positions::class);
    }

    public function absents()
    {
        return $this->hasMany(Absents::class);
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Employees;
use App\Departments;
use App\Positions;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.employee.index', [
            'title' => 'Karyawan | Welcome'
        ]);
    }

    public function employeesFirstView()
    {
        return view('admin.employee.indexFirst', [
            'title' => 'Karyawan | Welcome'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.employee.create', [
            'title' => 'Tambah Data Karyawan | Welcome'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [        
            'name' => 'required|min:10',
            'alamat'=> 'required|min:10',
            'status' => 'required'
        ]);

        Employees::create([
            'department_id' => 0,
            'position_id' => 0,
            'name' => $request->name,
            'email' => '-',
            'password' =>0,
            'tanggal_lahir' => $request->tl,
            'status' => $request->status,
            'gender' => '-',
            'address' => $request->alamat,
            'nomor_induk' => $request->nomor_induk,
            'start_work' => $request->tb
        ]);

        return redirect()->route('admin.employee.index')->with('success', 'Data Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Employees $employee)
    {
        return view('admin.employee.edit', [
            'title' => 'Update Karyawan | Welcome',
            'employee' => $employee,
            'departments' => Departments::orderBy('name', 'ASC')->get(),
            'positions' => Positions::orderBy('name', 'ASC')->get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employees $employee)
    {
        $employee->update([
            
            'name' => $request->name,
            'address' => $request->address,
            'nomor_induk' => $request->nomor_induk
        ]);

        return redirect()->route('admin.employee.index')->with('info', 'Data Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employees $employee)
    {
        $employee->delete();

        return redirect()->route('admin.employee.index')->with('danger', 'Data Berhasil Dihapus');
    }
}

resources/views/admin/employee/action.blade.php
<a href="{{ route('admin.employee.edit', $model) }}" class="btn btn-warning">Edit</a>

<button href="{{ route('admin.employee.destroy', $model) }}" class="btn btn-danger" id="delete">Hapus</button>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script>
    $('button#delete').on('click', function(e){
        e.preventDefault();

        var href = $(this).attr('href');

        Swal.fire({
        title: 'Apakah Yakin Hapus Data?',
        text: "Data yang sudah dihapus tidak bisa dikembalikan !",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Hapus'
        }).then((result) => {
        if (result.value) {
            
            document.getElementById('deleteForm').action = href;
            document.getElementById('deleteForm').submit();

            Swal.fire(
            'Terhapus',
            'Data kamu berhasil dihapus',
            'success'
            )
        }
    })

    })
</script>

resources/views/admin/employee/create.blade.php
@extends('admin.template.default')

@section('content')

<section class="content-header">
    <h1>
      Karyawan <small>Tambah Data</small>   
    </h1>
    <ol class="breadcrumb">
    <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('admin.department.index') }}"></i> Karyawan</a></li>
      <li class="active">Tambah Data Karyawan</li>
    </ol>
  </section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Tambah Data Karyawan</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" action="{{ route('admin.employee.store')}}" method="POST">
                @csrf
                <div class="box-body">
                    <div class="form-group @error('name') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Nama Karyawan</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" placeholder="Masukan Nama Karyawan" value="{{ old('name') }}">
                            @error('name')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('alamat') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Alamat Karyawan</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="alamat" placeholder="Masukan Alamat Karyawan" value="{{ old('alamat') }}">
                            @error('alamat')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('alamat') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Nomor Induk</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="nomor_induk" placeholder="Masukan Nomor Induk Karyawan">
                          
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('name') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Tanggal Lahir Karyawan</label>

                        <div class="col-sm-10">
                            <input type="date" class="form-control" name="tl" >
                          
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('tb') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Tanggal Bergabung Karyawan</label>

                        <div class="col-sm-10">
                            <input type="date" class="form-control" name="tb" >
                           
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('status') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Status</label>

                    <div class="col-sm-10">
                        <select name="status" class="form-control select2">
                            <option value="Aktif">Aktif</option>
                            <option value="Tidak aktif  ">Tidak Aktif</option>
                        </select>
                        @error('status')
                            <span class="help-block">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                <button type="submit" class="btn btn-info">Tambah Data</button>
                </div>
                <!-- /.box-footer -->
            </form>
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
<script>
    $( function() {
    $( "#date" ).datepicker();
  } );
</script>
@endsection

resources/views/admin/employee/edit.blade.php
@extends('admin.template.default')

@section('content')

<section class="content-header">
    <h1>
      Karyawan <small>Update Data</small>
    </h1>
    <ol class="breadcrumb">
    <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><a href="{{ route('admin.employee.index') }}">Karyawan</a></li>
      <li class="active">Update Karyawan</li>
    </ol>
  </section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Update Data Karyawan</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" action="{{ route('admin.employee.update', $employee)}}" method="POST">
                @csrf
                @method("PUT")
                <div class="box-body">
                    <div class="form-group @error('name') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Nama Karyawan</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" placeholder="Masukan Nama Karyawan" value="{{ old('name') ?? $employee->name }}">
                            @error('name')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('address') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Alamat</label>

                        <div class="col-sm-10">
                            <textarea name="address" rows="3" class="form-control">{{ old('address') ?? $employee->address }}</textarea>
                        
                            @error('address')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label">Nomor Induk</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="nomor_induk" placeholder="Nomor Induk Karyawan" value="{{ old('nomor_induk') ?? $employee->nomor_induk }}">
                           
                        </div>
                    </div>
                </div>

                

               
                   
                <!-- /.box-body -->
                <div class="box-footer">
                <button type="submit" class="btn btn-info">Update Data</button>
                </div>
                <!-- /.box-footer -->
            </form>
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

resources/views/admin/employee/index.blade.php
@extends('admin.template.default')

@section('content')
    
<section class="content-header">
  <h1>
    Karyawan    
  </h1>
  <ol class="breadcrumb">
  <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Karyawan</li>
  </ol>
</section>

<section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Data Karyawan</h3>

            <div style="float: right!important">
              <a href="{{ route('admin.employee.create') }}" class="btn btn-primary btn-sm">+ Tambah Data Karyawan</a>
            </div>
            &nbsp;
            <div style="float: right!important">
              <a href="{{ route('admin.employee.data.first.view') }}" class="btn btn-danger btn-sm">3 Data Pertama</a>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="dataTable" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>NO</th>
                <th>Nomor Induk</th>
                <th>Nama</th>
                <th>Alamat</th>               
                <th>Tanggal Lahir</th>
                <th>Tanggal Bergabung</th>                
                <th>Aksi</th>
              </tr>
              </thead>

              <tbody>

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</section>

@endsection

<form action="" method="post" id="deleteForm">
  @csrf
  @method("DELETE")
  <input type="submit" value="Hapus" style="display: none">
</form>

@push('script')

    <script src="{{ asset('admin/plugins/bs-notify.min.js') }}"></script>
  
    @include('admin.template.partials.alert')
    
    <script>
        $(function() {
          $('#dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('admin.employee.data') }}',
            columns: [
              { data: 'DT_RowIndex', orderable: false, searchable: false },
              { data: 'nomor_induk' },
              { data: 'name' },
              // { data: 'email' },
              // { data: '' },
              { data: 'address' },
              { data: 'tanggal_lahir' },
              { data: 'start_work' },
              { data: 'action' }
            ]
          })
        })
    </script>

@endpush

resources/views/admin/employee/indexfirst.blade.php
@extends('admin.template.default')

@section('content')
    
<section class="content-header">
  <h1>
    Karyawan    
  </h1>
  <ol class="breadcrumb">
  <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Karyawan</li>
  </ol>
</section>

<section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Data Karyawan</h3>

            <div style="float: right!important">
              <a href="{{ route('admin.employee.index') }}" class="btn btn-primary btn-sm">Kembali</a>
            </div>
           
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="dataTable" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>NO</th>
                <th>Nomor Induk</th>
                <th>Nama</th>
                <th>Alamat</th>               
                <th>Tanggal Lahir</th>
                <th>Tanggal Bergabung</th>                
                <th>Aksi</th>
              </tr>
              </thead>

              <tbody>

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</section>

@endsection

<form action="" method="post" id="deleteForm">
  @csrf
  @method("DELETE")
  <input type="submit" value="Hapus" style="display: none">
</form>

@push('script')

    <script src="{{ asset('admin/plugins/bs-notify.min.js') }}"></script>
  
    @include('admin.template.partials.alert')
    
    <script>
        $(function() {
          $('#dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('admin.employee.data.first') }}',
            columns: [
              { data: 'DT_RowIndex', orderable: false, searchable: false },
              { data: 'nomor_induk' },
              { data: 'name' },
              // { data: 'email' },
              // { data: '' },
              { data: 'address' },
              { data: 'tanggal_lahir' },
              { data: 'start_work' },
              { data: 'action' }
            ]
          })
        })
    </script>

@endpush