routes/admin.php
<?php

Route::get('/', 'HomeController@index')->name('dashboard');

Route::get('/department/data', 'DataController@departments')->name('department.data');
Route::resource('/department', 'DepartmentController');

Route::get('/position/data', 'DataController@positions')->name('position.data');
Route::resource('position', 'PositionController');

Route::get('/category/data', 'DataController@categories')->name('category.data');
Route::resource('category', 'CategoryController');

Route::get('/employee/data', 'DataController@employees')->name('employee.data');
Route::resource('employee', 'EmployeeController');
Route::get('/employe/data/first','DataController@employeesFirst')->name('employee.data.first');
Route::get('/employe/data/first/view','EmployeeController@employeesFirstView')->name('employee.data.first.view');

Route::get('/absent/data', 'DataController@absents')->name('absent.data');
Route::resource('absent', 'AbsentController');

Route::get('/benefit/data', 'DataController@benefits')->name('benefit.data');
Route::resource('benefit', 'BenefitController');

Route::resource('laporan', 'LaporanController');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

app/Benefits.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Benefits extends Model
{
    protected $guarded = [];

    public $timestamps = false;

    public function employee()
    {
        return $this->belongsTo(Employees::class);
    }

    public function categorie()
    {
        return $this->belongsTo(Categories::class);
    }
}

app/Http/Controllers/Admin/BenefitController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Benefits;
use App\Employees;
use App\Categories;

class BenefitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.benefit.index', [
            'title' => 'Gaji & Tunjangan | Welcome'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.benefit.create', [
            'title' => 'Tambah Gaji & Tunjangan | Welcome',
            'employees' => Employees::orderBy('name', 'ASC')->get(),
            'categories' => Categories::orderBy('name', 'ASC')->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'employee_id' => 'required',
            'categorie_id' => 'required',
            'nominal' => 'required',
            'status' => 'required'
        ]);

        Benefits::create([
            'employee_id' => $request->employee_id,
            'categorie_id' => $request->categorie_id,
            'nominal' => $request->nominal,
            'status' => $request->status
        ]);

        return redirect()->route('admin.benefit.index')->with('success', 'Data Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Benefits $benefit)
    {
        return view('admin.benefit.edit', [
            'title' => 'Update Gaji | Welcome',
            'benefit' => $benefit,
            'employees' => Employees::orderBy('name', 'ASC')->get(),
            'categories' => Categories::orderBy('name', 'ASC')->get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Benefits $benefit)
    {
        $benefit->update([
            'employee_id' => $request->employee_id,
            'categorie_id' => $request->categorie_id,
            'nominal' => $request->nominal,
            'status' => $request->status
        ]);

        return redirect()->route('admin.benefit.index')->with('info', 'Data Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Benefits $benefit)
    {
        $benefit->delete();

        return redirect()->route('admin.benefit.index')->with('danger', 'Data Berhasil Dihapus');
    }
}

resources/views/admin/benefit/action.blade.php
<a href="{{ route('admin.benefit.edit', $model) }}" class="btn btn-warning">Edit</a>

<button href="{{ route('admin.benefit.destroy', $model) }}" class="btn btn-danger" id="delete">Hapus</button>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script>
    $('button#delete').on('click', function(e){
        e.preventDefault();

        var href = $(this).attr('href');

        Swal.fire({
        title: 'Apakah Yakin Hapus Data?',
        text: "Data yang sudah dihapus tidak bisa dikembalikan !",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Hapus'
        }).then((result) => {
        if (result.value) {
            
            document.getElementById('deleteForm').action = href;
            document.getElementById('deleteForm').submit();

            Swal.fire(
            'Terhapus',
            'Data kamu berhasil dihapus',
            'success'
            )
        }
    })

    })
</script>

resources/views/admin/benefit/create.blade.php
@extends('admin.template.default')

@section('content')

<section class="content-header">
    <h1>
      Gaji & Tunjangan <small>Tambah Data</small>   
    </h1>
    <ol class="breadcrumb">
    <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('admin.benefit.index') }}"></i> Gaji & Tunjangan</a></li>
      <li class="active">Tambah Data Gaji & Tunjangan</li>
    </ol>
  </section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Tambah Data Gaji & Tunjangan</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" action="{{ route('admin.benefit.store')}}" method="POST">
                @csrf
                
                <div class="box-body">
                    <div class="form-group @error('name') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Nama Karyawan</label>

                        <div class="col-sm-10">
                            <select name="employee_id" class="form-control select2">
                                @foreach ($employees as $employee)
                                <option value="{{ $employee->id }}">{{ $employee->name }}</option>
                            @endforeach
                            </select>
                            @error('employee_id')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                
                <div class="box-body">
                    <div class="form-group @error('name') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Kategori</label>

                        <div class="col-sm-10">
                            <select name="categorie_id" class="form-control select2">
                                @foreach ($categories as $categorie)
                                <option value="{{ $categorie->id }}">{{ $categorie->name }}</option>
                            @endforeach
                            </select>
                            @error('categorie_id')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                
                <div class="box-body">
                    <div class="form-group @error('nominal') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Nominal</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="nominal" placeholder="Masukan Nominal" value="{{ old('nominal') }}">
                            @error('nominal')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('status') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Status</label>

                        <div class="col-sm-10">
                            <select name="status" class="form-control select2">
                                <option value="Aktif">Aktif</option>
                                <option value="Tidak aktif  ">Tidak Aktif</option>
                            </select>
                            @error('status')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>             
                
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                <button type="submit" class="btn btn-info">Tambah Data</button>
                </div>
                <!-- /.box-footer -->
            </form>
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

resources/views/admin/benefit/edit.blade.php
@extends('admin.template.default')

@section('content')

<section class="content-header">
    <h1>
      Gaji & Tunjangan  <small>Update Data</small>  
    </h1>
    <ol class="breadcrumb">
    <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><a href="{{ route('admin.benefit.index') }}">Gaji & Tunjangan</a></li>
      <li class="active">Update Gaji & Tunjangan</li>
    </ol>
  </section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Update Data Gaji & Tunjangan</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" action="{{ route('admin.benefit.update', $benefit)}}" method="POST">
                @csrf
                @method("PUT")

                <div class="box-body">
                    <div class="form-group @error('employee_id') has-error @enderror">
                        <label class="col-sm-2 control-label">Nama Karyawan</label>

                        <div class="col-sm-10">
                            <select name="employee_id" class="form-control select2">
                                @foreach ($employees as $employee)
                                    <option 
                                        value="{{ $employee->id }}"
                                        @if ($employee->id === $benefit->employee_id)
                                            selected
                                        @endif
                                        >
                                        {{ $employee->name }}
                                    </option>
                                @endforeach
                            </select>
                            @error('employee_id')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('categorie_id') has-error @enderror">
                        <label class="col-sm-2 control-label">Kategori</label>

                        <div class="col-sm-10">
                            <select name="categorie_id" class="form-control select2">
                                @foreach ($categories as $categorie)
                                    <option 
                                        value="{{ $categorie->id }}"
                                        @if ($categorie->id === $benefit->categorie_id)
                                            selected
                                        @endif
                                        >
                                        {{ $categorie->name }}
                                    </option>
                                @endforeach
                            </select>
                            @error('categorie_id')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>                    
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('nominal') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Nominal</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="nominal" placeholder="Jenis Kelamin" value="{{ old('nominal') ?? $benefit->nominal }}">
                            @error('nominal')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group @error('status') has-error @enderror">
                        <label for="" class="col-sm-2 control-label">Status</label>

                        <div class="col-sm-10">
                            <select name="status" class="form-control select2">
                                <option value="Aktif">Aktif</option>
                                <option value="Tidak aktif  ">Tidak Aktif</option>
                            </select>
                            @error('status')
                                <span class="help-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                
                <!-- /.box-body -->
                <div class="box-footer">
                <button type="submit" class="btn btn-info">Update Data</button>
                </div>
                <!-- /.box-footer -->
            </form>
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

resources/views/admin/benefit/index.blade.php
@extends('admin.template.default')

@section('content')

<section class="content-header">
  <h1>
    Gaji & Tunjangan    
  </h1>
  <ol class="breadcrumb">
  <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Gaji & Tunjangan</li>
  </ol>
</section>
    
<section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Data Gaji & Tunjangan</h3>
            
            <div style="float: right!important">
              <a href="{{ route('admin.benefit.create') }}" class="btn btn-primary btn-sm">+ Tambah Data Gaji & Tunjangan</a>
            </div>

          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="dataTable" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>NO</th>
                <th>Nama Karyawan</th>
                <th>Kategori</th>
                <th>Nominal</th>                
                <th>Status</th>                
                <th>Aksi</th>
              </tr>
              </thead>
            </table>
          </div>
        </div>
      </div>
    </div>
</section>

<form action="" method="post" id="deleteForm">
  @csrf
  @method("DELETE")
  <input type="submit" value="Hapus" style="display: none">
</form>

@endsection

@push('script')
    
    <script src="{{ asset('admin/plugins/bs-notify.min.js') }}"></script>
  
    @include('admin.template.partials.alert')

    <script>
        $(function() {
          $('#dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('admin.benefit.data') }}',
            columns: [
              { data: 'DT_RowIndex', orderable: false, searchable: false },
              { data: 'employee' },
              { data: 'categorie' },
              { data: 'nominal' },
              { data: 'status' },
              { data: 'action' }
            ]
          })
        })
    </script>

@endpush